obj-m += amvdec_ports.o
amvdec_ports-objs += aml_vcodec_dec_drv.o
amvdec_ports-objs += aml_vcodec_dec.o
amvdec_ports-objs += aml_vcodec_util.o
amvdec_ports-objs += aml_vcodec_adapt.o
amvdec_ports-objs += aml_vcodec_vpp.o
amvdec_ports-objs += aml_vcodec_ge2d.o
amvdec_ports-objs += vdec_drv_if.o
amvdec_ports-objs += aml_task_chain.o
amvdec_ports-objs += decoder/vdec_h264_if.o
amvdec_ports-objs += decoder/vdec_hevc_if.o
amvdec_ports-objs += decoder/vdec_vp9_if.o
amvdec_ports-objs += decoder/vdec_mpeg12_if.o
amvdec_ports-objs += decoder/vdec_mpeg4_if.o
amvdec_ports-objs += decoder/vdec_mjpeg_if.o
amvdec_ports-objs += decoder/vdec_avs_if.o
amvdec_ports-objs += decoder/vdec_av1_if.o
amvdec_ports-objs += decoder/vdec_avs2_if.o
ifdef CONFIG_AMLOGIC_MEDIA_V4L_SOFTWARE_PARSER
amvdec_ports-objs += decoder/aml_h264_parser.o
amvdec_ports-objs += decoder/aml_hevc_parser.o
amvdec_ports-objs += decoder/aml_vp9_parser.o
amvdec_ports-objs += decoder/aml_mpeg12_parser.o
amvdec_ports-objs += decoder/aml_mpeg4_parser.o
amvdec_ports-objs += decoder/aml_mjpeg_parser.o
amvdec_ports-objs += utils/golomb.o
endif
amvdec_ports-objs += utils/common.o
