obj-$(CONFIG_AM_WIFI) +=  wifi_dt.o
obj-$(CONFIG_BCMDHD_USE_STATIC_BUF) += dhd_static_buf.o
obj-$(CONFIG_AM_WIFI_DUMMY) += wifi_dummy.o
obj-$(CONFIG_AM_WIFI_USB) += wifi_power.o
obj-$(CONFIG_BCMDHD) += bcmdhd/
