#
# Makefile for TVAFE.
#
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_TVIN_AFE) += vin/tvin/tvafe/tvafe_cvd.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_TVIN_AFE) += vin/tvin/tvafe/tvafe_general.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_TVIN_AFE) += vin/tvin/tvafe/tvafe_debug.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_TVIN_AFE) += vin/tvin/tvafe/tvafe_pq_table.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_TVIN_AFE) += vin/tvin/tvafe/tvafe.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_TVIN_VBI) += vin/tvin/tvafe/tvafe_vbi.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_TVIN_AVDETECT) += vin/tvin/tvafe/tvafe_avin_detect.o

