# Makefile for FB and VOUT

obj-$(CONFIG_AM_FB) += osd/
obj-$(CONFIG_AM_FB_EXT) += osd_ext/
obj-$(CONFIG_AM_VOUT) += vout/
obj-$(CONFIG_AM_VOUT2) += vout2/
obj-$(CONFIG_AM_GE2D) += ge2d/
obj-$(CONFIG_AM_LOGO) += logo/
obj-$(CONFIG_AML_LCD) += lcd/
obj-$(CONFIG_AML_BACKLIGHT) += backlight/
