ifdef CONFIG_AMLOGIC_LINUX_STD_CEC
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_AO_CEC)  += cec/std_ao_cec.o cec/hdmi_aocec_api.o cec/hdmi_cec_dump.o
else
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_AO_CEC)  += cec/hdmi_ao_cec.o cec/hdmi_aocec_api.o cec/hdmi_cec_dump.o
endif
