/*
 * drivers/amlogic/media/enhancement/amvecm/arch/vpp_dolbyvision_regs.h
 *
 * Copyright (C) 2017 Amlogic, Inc. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 */

#ifndef VPP_DOLBYVISION_REGS_H
#define VPP_DOLBYVISION_REGS_H

#define CORE1_OFFSET             (0x1UL << 24)
#define CORE1_1_OFFSET           (0x1UL << 25)
#define CORE2A_OFFSET            (0x1UL << 26)
#define CORE3_OFFSET             (0x1UL << 27)
#define CORETV_OFFSET            (0x1UL << 28)

#define DOLBY_CORE1_REG_START		(0x00 + CORE1_OFFSET)
#define DOLBY_CORE1_CLKGATE_CTRL	(0xf2 + CORE1_OFFSET)
#define DOLBY_CORE1_SWAP_CTRL0		(0xf3 + CORE1_OFFSET)
#define DOLBY_CORE1_SWAP_CTRL1		(0xf4 + CORE1_OFFSET)
#define DOLBY_CORE1_SWAP_CTRL2		(0xf5 + CORE1_OFFSET)
#define DOLBY_CORE1_SWAP_CTRL3		(0xf6 + CORE1_OFFSET)
#define DOLBY_CORE1_SWAP_CTRL4		(0xf7 + CORE1_OFFSET)
#define DOLBY_CORE1_SWAP_CTRL5		(0xf8 + CORE1_OFFSET)
#define DOLBY_CORE1_DMA_CTRL		(0xf9 + CORE1_OFFSET)
#define DOLBY_CORE1_DMA_STATUS		(0xfa + CORE1_OFFSET)
#define DOLBY_CORE1_STATUS0		(0xfb + CORE1_OFFSET)
#define DOLBY_CORE1_STATUS1		(0xfc + CORE1_OFFSET)
#define DOLBY_CORE1_STATUS2		(0xfd + CORE1_OFFSET)
#define DOLBY_CORE1_STATUS3		(0xfe + CORE1_OFFSET)
#define DOLBY_CORE1_DMA_PORT		(0xff + CORE1_OFFSET)

#define DOLBY_CORE1_1_REG_START		(0x00 + CORE1_1_OFFSET)
#define DOLBY_CORE1_1_CLKGATE_CTRL	(0xf2 + CORE1_1_OFFSET)
#define DOLBY_CORE1_1_SWAP_CTRL0	(0xf3 + CORE1_1_OFFSET)
#define DOLBY_CORE1_1_SWAP_CTRL1	(0xf4 + CORE1_1_OFFSET)
#define DOLBY_CORE1_1_SWAP_CTRL2	(0xf5 + CORE1_1_OFFSET)
#define DOLBY_CORE1_1_SWAP_CTRL3	(0xf6 + CORE1_1_OFFSET)
#define DOLBY_CORE1_1_SWAP_CTRL4	(0xf7 + CORE1_1_OFFSET)
#define DOLBY_CORE1_1_SWAP_CTRL5	(0xf8 + CORE1_1_OFFSET)
#define DOLBY_CORE1_1_DMA_CTRL		(0xf9 + CORE1_1_OFFSET)
#define DOLBY_CORE1_1_DMA_STATUS	(0xfa + CORE1_1_OFFSET)
#define DOLBY_CORE1_1_STATUS0		(0xfb + CORE1_1_OFFSET)
#define DOLBY_CORE1_1_STATUS1		(0xfc + CORE1_1_OFFSET)
#define DOLBY_CORE1_1_STATUS2		(0xfd + CORE1_1_OFFSET)
#define DOLBY_CORE1_1_STATUS3		(0xfe + CORE1_1_OFFSET)
#define DOLBY_CORE1_1_DMA_PORT		(0xff + CORE1_1_OFFSET)

#define DOLBY_CORE2A_REG_START		(0x00 + CORE2A_OFFSET)
#define DOLBY_CORE2A_CTRL		(0x01 + CORE2A_OFFSET)
#define DOLBY_CORE2A_CLKGATE_CTRL	(0x32 + CORE2A_OFFSET)
#define DOLBY_CORE2A_SWAP_CTRL0		(0x33 + CORE2A_OFFSET)
#define DOLBY_CORE2A_SWAP_CTRL1		(0x34 + CORE2A_OFFSET)
#define DOLBY_CORE2A_SWAP_CTRL2		(0x35 + CORE2A_OFFSET)
#define DOLBY_CORE2A_SWAP_CTRL3		(0x36 + CORE2A_OFFSET)
#define DOLBY_CORE2A_SWAP_CTRL4		(0x37 + CORE2A_OFFSET)
#define DOLBY_CORE2A_SWAP_CTRL5		(0x38 + CORE2A_OFFSET)
#define DOLBY_CORE2A_DMA_CTRL		(0x39 + CORE2A_OFFSET)
#define DOLBY_CORE2A_DMA_STATUS		(0x3a + CORE2A_OFFSET)
#define DOLBY_CORE2A_STATUS0		(0x3b + CORE2A_OFFSET)
#define DOLBY_CORE2A_STATUS1		(0x3c + CORE2A_OFFSET)
#define DOLBY_CORE2A_STATUS2		(0x3d + CORE2A_OFFSET)
#define DOLBY_CORE2A_STATUS3		(0x3e + CORE2A_OFFSET)
#define DOLBY_CORE2A_DMA_PORT		(0x3f + CORE2A_OFFSET)

#define DOLBY_CORE3_REG_START		(0x00 + CORE3_OFFSET)
#define DOLBY_CORE3_CLKGATE_CTRL	(0xf0 + CORE3_OFFSET)
#define DOLBY_CORE3_SWAP_CTRL0		(0xf1 + CORE3_OFFSET)
#define DOLBY_CORE3_SWAP_CTRL1		(0xf2 + CORE3_OFFSET)
#define DOLBY_CORE3_SWAP_CTRL2		(0xf3 + CORE3_OFFSET)
#define DOLBY_CORE3_SWAP_CTRL3		(0xf4 + CORE3_OFFSET)
#define DOLBY_CORE3_SWAP_CTRL4		(0xf5 + CORE3_OFFSET)
#define DOLBY_CORE3_SWAP_CTRL5		(0xf6 + CORE3_OFFSET)
#define DOLBY_CORE3_SWAP_CTRL6		(0xf7 + CORE3_OFFSET)
#define DOLBY_CORE3_DIAG_CTRL		(0xf8 + CORE3_OFFSET)
#define DOLBY_CORE3_CRC_CTRL		(0xfb + CORE3_OFFSET)
#define DOLBY_CORE3_INPUT_CSC_CRC	(0xfc + CORE3_OFFSET)
#define DOLBY_CORE3_OUTPUT_CSC_CRC	(0xfd + CORE3_OFFSET)

#define DOLBY_TV_REG_START		(0x00 + CORETV_OFFSET)
#define DOLBY_TV_CLKGATE_CTRL		(0xf1 + CORETV_OFFSET)
#define DOLBY_TV_SWAP_CTRL0		(0xf2 + CORETV_OFFSET)
#define DOLBY_TV_SWAP_CTRL1		(0xf3 + CORETV_OFFSET)
#define DOLBY_TV_SWAP_CTRL2		(0xf4 + CORETV_OFFSET)
#define DOLBY_TV_SWAP_CTRL3		(0xf5 + CORETV_OFFSET)
#define DOLBY_TV_SWAP_CTRL4		(0xf6 + CORETV_OFFSET)
#define DOLBY_TV_SWAP_CTRL5		(0xf7 + CORETV_OFFSET)
#define DOLBY_TV_SWAP_CTRL6		(0xf8 + CORETV_OFFSET)
#define DOLBY_TV_SWAP_CTRL7		(0xf9 + CORETV_OFFSET)
#define DOLBY_TV_AXI2DMA_CTRL0		(0xfa + CORETV_OFFSET)
#define DOLBY_TV_AXI2DMA_CTRL1		(0xfb + CORETV_OFFSET)
#define DOLBY_TV_AXI2DMA_CTRL2		(0xfc + CORETV_OFFSET)
#define DOLBY_TV_AXI2DMA_CTRL3		(0xfd + CORETV_OFFSET)
#define DOLBY_TV_STATUS0		(0xfe + CORETV_OFFSET)
#define DOLBY_TV_STATUS1		(0xff + CORETV_OFFSET)
#define DOLBY_TV_DIAG_CTRL		(0xe7 + CORETV_OFFSET)
#define DOLBY_TV_CRC_CTRL		(0xea + CORETV_OFFSET)
#define DOLBY_TV_OUTPUT_DM_CRC		(0xef + CORETV_OFFSET)


#define VPP_WRAP_OSD1_MATRIX_EN_CTRL    0x3d6d
#define VPP_WRAP_OSD2_MATRIX_EN_CTRL    0x3d7d
#define VPP_WRAP_OSD3_MATRIX_EN_CTRL    0x3dbd
#define DOLBY_PATH_CTRL			0x1a0c
#define VIU_MISC_CTRL1			0x1a07
#define VPP_DOLBY_CTRL			0x1d93
#define VIU_SW_RESET			0x1a01
#define VPU_HDMI_FMT_CTRL		0x2743

#endif
