$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BACKLIGHT) += vout/lcd/backlight/lcd_bl.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BACKLIGHT) += vout/lcd/backlight/bl_pwm.o

#ifdef CONFIG_AMLOGIC_BACKLIGHT
include drivers/amlogic/media/vout/lcd/backlight/bl_extern/Makefile
include drivers/amlogic/media/vout/lcd/backlight/bl_ldim/Makefile
#endif
