$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BACKLIGHT) += vout/lcd/backlight/aml_bl.o

include drivers/amlogic/media/vout/lcd/backlight/bl_extern/Makefile

include drivers/amlogic/media/vout/lcd/backlight/aml_ldim/Makefile

