#
# AMLOGIC vpq.
#

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_VPQ) += vpq/vpq_drv.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_VPQ) += vpq/vpq_debug.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_VPQ) += vpq/vpq_ioctl.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_VPQ) += vpq/vpq_def_table.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_VPQ) += vpq/vpq_table_logic.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_VPQ) += vpq/vpq_vfm.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_VPQ) += vpq/vpq_processor.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_VPQ) += vpq/modules/vpq_module_cm.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_VPQ) += vpq/modules/vpq_module_timing.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_VPQ) += vpq/modules/vpq_module_gamma.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_VPQ) += vpq/modules/vpq_module_dump.o