#
# Makefile for the amlogic video device interface device drivers.
#
asflags-y += -mfloat-abi=softfp -mfpu=neon

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_UTILS) += video_processor/utils/vfutil.o

