obj-$(CONFIG_AMLOGIC_IRBLASTER_CORE) += core.o sysfs.o
obj-$(CONFIG_AMLOGIC_IRBLASTER_MESON) += irblaster-meson.o aml-irblaster.o
obj-$(CONFIG_AMLOGIC_IRBLASTER_PROTOCOL) += encoder.o irblaster-nec-encoder.o \
					    irblaster-rca-encoder.o
