# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_VIDEO_RK_SER_RKX11X)	+= rkx11x/

rkcam-dummy-objs := dummy.o
rkcam-ar0330-objs := ar0330.o
rkcam-os04a10-objs := os04a10.o
rkcam-gc2145-objs := gc2145.o

obj-$(CONFIG_VIDEO_RK_CAM_DUMMY)	+= rkcam-dummy.o
obj-$(CONFIG_VIDEO_RK_CAM_AR0330)	+= rkcam-ar0330.o
obj-$(CONFIG_VIDEO_RK_CAM_OS04A10)	+= rkcam-os04a10.o
obj-$(CONFIG_VIDEO_RK_CAM_GC2145)	+= rkcam-gc2145.o