/* SPDX-License-Identifier: GPL-2.0 */
/* Copyright (c) 2025 Rockchip Electronics Co., Ltd. */

#ifndef _RKVPSS_REGS_V20_H
#define _RKVPSS_REGS_V20_H

/* VPSS */
#define RKVPSS2X_VPSS_BASE			0x0000
#define RKVPSS2X_VPSS_PIPE_ACK2			(RKVPSS2X_VPSS_BASE + 0xb8)
#define RKVPSS2X_VPSS_FRAME_CNT			(RKVPSS2X_VPSS_BASE + 0xc8)
#define RKVPSS2X_VPSS2ENC_DEBUG			(RKVPSS2X_VPSS_BASE + 0xcc)

/* CMSC identical */

/* CROP */
#define RKVPSS2X_CROP0_BASE			0x0700
#define RKVPSS2X_CROP0_4_OFFS			(RKVPSS2X_CROP0_BASE + 0x50)
#define RKVPSS2X_CROP0_4_SIZE			(RKVPSS2X_CROP0_BASE + 0x54)
#define RKVPSS2X_CROP0_5_OFFS			(RKVPSS2X_CROP0_BASE + 0x58)
#define RKVPSS2X_CROP0_5_SIZE			(RKVPSS2X_CROP0_BASE + 0x5c)
#define RKVPSS2X_CROP0_4_OFFS_SHD		(RKVPSS2X_CROP0_BASE + 0xb0)
#define RKVPSS2X_CROP0_4_SIZE_SHD		(RKVPSS2X_CROP0_BASE + 0xb4)
#define RKVPSS2X_CROP0_5_OFFS_SHD		(RKVPSS2X_CROP0_BASE + 0xb8)
#define RKVPSS2X_CROP0_5_SIZE_SHD		(RKVPSS2X_CROP0_BASE + 0xbc)

#define RKVPSS2X_CROP1_BASE			0x0800
#define RKVPSS2X_CROP1_4_OFFS			(RKVPSS2X_CROP1_BASE + 0x50)
#define RKVPSS2X_CROP1_4_SIZE			(RKVPSS2X_CROP1_BASE + 0x54)
#define RKVPSS2X_CROP1_5_OFFS			(RKVPSS2X_CROP1_BASE + 0x58)
#define RKVPSS2X_CROP1_5_SIZE			(RKVPSS2X_CROP1_BASE + 0x5c)
#define RKVPSS2X_CROP1_4_OFFS_SHD		(RKVPSS2X_CROP1_BASE + 0xb0)
#define RKVPSS2X_CROP1_4_SIZE_SHD		(RKVPSS2X_CROP1_BASE + 0xb4)
#define RKVPSS2X_CROP1_5_OFFS_SHD		(RKVPSS2X_CROP1_BASE + 0xb8)
#define RKVPSS2X_CROP1_5_SIZE_SHD		(RKVPSS2X_CROP1_BASE + 0xbc)

/* Bilinear scale channel0 */
#define RKVPSS2X_SCALE0_BASE			0x1000
#define RKVPSS2X_SCALE0_CTRL			(RKVPSS2X_SCALE0_BASE + 0x00)
#define RKVPSS2X_SCALE0_UPDATE			(RKVPSS2X_SCALE0_BASE + 0x04)
#define RKVPSS2X_SCALE0_SRC_SIZE		(RKVPSS2X_SCALE0_BASE + 0x08)
#define RKVPSS2X_SCALE0_DST_SIZE		(RKVPSS2X_SCALE0_BASE + 0x0c)
#define RKVPSS2X_SCALE0_HY_FAC			(RKVPSS2X_SCALE0_BASE + 0x10)
#define RKVPSS2X_SCALE0_HC_FAC			(RKVPSS2X_SCALE0_BASE + 0x14)
#define RKVPSS2X_SCALE0_VY_FAC			(RKVPSS2X_SCALE0_BASE + 0x18)
#define RKVPSS2X_SCALE0_VC_FAC			(RKVPSS2X_SCALE0_BASE + 0x1c)
#define RKVPSS2X_SCALE0_HY_OFFS			(RKVPSS2X_SCALE0_BASE + 0x20)
#define RKVPSS2X_SCALE0_HC_OFFS			(RKVPSS2X_SCALE0_BASE + 0x24)
#define RKVPSS2X_SCALE0_VY_OFFS			(RKVPSS2X_SCALE0_BASE + 0x28)
#define RKVPSS2X_SCALE0_VC_OFFS			(RKVPSS2X_SCALE0_BASE + 0x2c)
#define RKVPSS2X_SCALE0_HY_SIZE			(RKVPSS2X_SCALE0_BASE + 0x40)
#define RKVPSS2X_SCALE0_HC_SIZE			(RKVPSS2X_SCALE0_BASE + 0x44)
#define RKVPSS2X_SCALE0_HY_OFFS_MI		(RKVPSS2X_SCALE0_BASE + 0x48)
#define RKVPSS2X_SCALE0_HC_OFFS_MI		(RKVPSS2X_SCALE0_BASE + 0x4c)
#define RKVPSS2X_SCALE0_IN_CROP_OFFSET		(RKVPSS2X_SCALE0_BASE + 0x50)
#define RKVPSS2X_SCALE0_CTRL_SHD		(RKVPSS2X_SCALE0_BASE + 0x80)
#define RKVPSS2X_SCALE0_SRC_SIZE_SHD		(RKVPSS2X_SCALE0_BASE + 0x88)
#define RKVPSS2X_SCALE0_DST_SIZE_SHD		(RKVPSS2X_SCALE0_BASE + 0x8c)
#define RKVPSS2X_SCALE0_HY_FAC_SHD		(RKVPSS2X_SCALE0_BASE + 0x90)
#define RKVPSS2X_SCALE0_HC_FAC_SHD		(RKVPSS2X_SCALE0_BASE + 0x94)
#define RKVPSS2X_SCALE0_VY_FAC_SHD		(RKVPSS2X_SCALE0_BASE + 0x98)
#define RKVPSS2X_SCALE0_VC_FAC_SHD		(RKVPSS2X_SCALE0_BASE + 0x9c)
#define RKVPSS2X_SCALE0_HY_OFFS_SHD		(RKVPSS2X_SCALE0_BASE + 0xa0)
#define RKVPSS2X_SCALE0_HC_OFFS_SHD		(RKVPSS2X_SCALE0_BASE + 0xa4)
#define RKVPSS2X_SCALE0_VY_OFFS_SHD		(RKVPSS2X_SCALE0_BASE + 0xa8)
#define RKVPSS2X_SCALE0_VC_OFFS_SHD		(RKVPSS2X_SCALE0_BASE + 0xac)
#define RKVPSS2X_SCALE0_HY_SIZE_SHD		(RKVPSS2X_SCALE0_BASE + 0xc0)
#define RKVPSS2X_SCALE0_HC_SIZE_SHD		(RKVPSS2X_SCALE0_BASE + 0xc4)
#define RKVPSS2X_SCALE0_HY_OFFS_MI_SHD		(RKVPSS2X_SCALE0_BASE + 0xc8)
#define RKVPSS2X_SCALE0_HC_OFFS_MI_SHD		(RKVPSS2X_SCALE0_BASE + 0xcc)
#define RKVPSS2X_SCALE0_IN_CROP_OFFSET_SHD	(RKVPSS2X_SCALE0_BASE + 0xd0)

/* Bilinear scale channel4 */
#define RKVPSS2X_SCALE4_BASE			0x0a00
#define RKVPSS2X_SCALE4_CTRL			(RKVPSS2X_SCALE4_BASE + 0x00)
#define RKVPSS2X_SCALE4_UPDATE			(RKVPSS2X_SCALE4_BASE + 0x04)
#define RKVPSS2X_SCALE4_SRC_SIZE		(RKVPSS2X_SCALE4_BASE + 0x08)
#define RKVPSS2X_SCALE4_DST_SIZE		(RKVPSS2X_SCALE4_BASE + 0x0c)
#define RKVPSS2X_SCALE4_HY_FAC			(RKVPSS2X_SCALE4_BASE + 0x10)
#define RKVPSS2X_SCALE4_HC_FAC			(RKVPSS2X_SCALE4_BASE + 0x14)
#define RKVPSS2X_SCALE4_VY_FAC			(RKVPSS2X_SCALE4_BASE + 0x18)
#define RKVPSS2X_SCALE4_VC_FAC			(RKVPSS2X_SCALE4_BASE + 0x1c)
#define RKVPSS2X_SCALE4_HY_OFFS			(RKVPSS2X_SCALE4_BASE + 0x20)
#define RKVPSS2X_SCALE4_HC_OFFS			(RKVPSS2X_SCALE4_BASE + 0x24)
#define RKVPSS2X_SCALE4_VY_OFFS			(RKVPSS2X_SCALE4_BASE + 0x28)
#define RKVPSS2X_SCALE4_VC_OFFS			(RKVPSS2X_SCALE4_BASE + 0x2c)
#define RKVPSS2X_SCALE4_HY_SIZE			(RKVPSS2X_SCALE4_BASE + 0x40)
#define RKVPSS2X_SCALE4_HC_SIZE			(RKVPSS2X_SCALE4_BASE + 0x44)
#define RKVPSS2X_SCALE4_HY_OFFS_MI		(RKVPSS2X_SCALE4_BASE + 0x48)
#define RKVPSS2X_SCALE4_HC_OFFS_MI		(RKVPSS2X_SCALE4_BASE + 0x4c)
#define RKVPSS2X_SCALE4_IN_CROP_OFFSET		(RKVPSS2X_SCALE4_BASE + 0x50)
#define RKVPSS2X_SCALE4_CTRL_SHD		(RKVPSS2X_SCALE4_BASE + 0x80)
#define RKVPSS2X_SCALE4_SRC_SIZE_SHD		(RKVPSS2X_SCALE4_BASE + 0x88)
#define RKVPSS2X_SCALE4_DST_SIZE_SHD		(RKVPSS2X_SCALE4_BASE + 0x8c)
#define RKVPSS2X_SCALE4_HY_FAC_SHD		(RKVPSS2X_SCALE4_BASE + 0x90)
#define RKVPSS2X_SCALE4_HC_FAC_SHD		(RKVPSS2X_SCALE4_BASE + 0x94)
#define RKVPSS2X_SCALE4_VY_FAC_SHD		(RKVPSS2X_SCALE4_BASE + 0x98)
#define RKVPSS2X_SCALE4_VC_FAC_SHD		(RKVPSS2X_SCALE4_BASE + 0x9c)
#define RKVPSS2X_SCALE4_HY_OFFS_SHD		(RKVPSS2X_SCALE4_BASE + 0xa0)
#define RKVPSS2X_SCALE4_HC_OFFS_SHD		(RKVPSS2X_SCALE4_BASE + 0xa4)
#define RKVPSS2X_SCALE4_VY_OFFS_SHD		(RKVPSS2X_SCALE4_BASE + 0xa8)
#define RKVPSS2X_SCALE4_VC_OFFS_SHD		(RKVPSS2X_SCALE4_BASE + 0xac)
#define RKVPSS2X_SCALE4_HY_SIZE_SHD		(RKVPSS2X_SCALE4_BASE + 0xc0)
#define RKVPSS2X_SCALE4_HC_SIZE_SHD		(RKVPSS2X_SCALE4_BASE + 0xc4)
#define RKVPSS2X_SCALE4_HY_OFFS_MI_SHD		(RKVPSS2X_SCALE4_BASE + 0xc8)
#define RKVPSS2X_SCALE4_HC_OFFS_MI_SHD		(RKVPSS2X_SCALE4_BASE + 0xcc)
#define RKVPSS2X_SCALE4_IN_CROP_OFFSET_SHD	(RKVPSS2X_SCALE4_BASE + 0xd0)

/* Bilinear scale channel5 */
#define RKVPSS2X_SCALE5_BASE			0x0c00
#define RKVPSS2X_SCALE5_CTRL			(RKVPSS2X_SCALE5_BASE + 0x00)
#define RKVPSS2X_SCALE5_UPDATE			(RKVPSS2X_SCALE5_BASE + 0x04)
#define RKVPSS2X_SCALE5_SRC_SIZE		(RKVPSS2X_SCALE5_BASE + 0x08)
#define RKVPSS2X_SCALE5_DST_SIZE		(RKVPSS2X_SCALE5_BASE + 0x0c)
#define RKVPSS2X_SCALE5_HY_FAC			(RKVPSS2X_SCALE5_BASE + 0x10)
#define RKVPSS2X_SCALE5_HC_FAC			(RKVPSS2X_SCALE5_BASE + 0x14)
#define RKVPSS2X_SCALE5_VY_FAC			(RKVPSS2X_SCALE5_BASE + 0x18)
#define RKVPSS2X_SCALE5_VC_FAC			(RKVPSS2X_SCALE5_BASE + 0x1c)
#define RKVPSS2X_SCALE5_HY_OFFS			(RKVPSS2X_SCALE5_BASE + 0x20)
#define RKVPSS2X_SCALE5_HC_OFFS			(RKVPSS2X_SCALE5_BASE + 0x24)
#define RKVPSS2X_SCALE5_VY_OFFS			(RKVPSS2X_SCALE5_BASE + 0x28)
#define RKVPSS2X_SCALE5_VC_OFFS			(RKVPSS2X_SCALE5_BASE + 0x2c)
#define RKVPSS2X_SCALE5_HY_SIZE			(RKVPSS2X_SCALE5_BASE + 0x40)
#define RKVPSS2X_SCALE5_HC_SIZE			(RKVPSS2X_SCALE5_BASE + 0x44)
#define RKVPSS2X_SCALE5_HY_OFFS_MI		(RKVPSS2X_SCALE5_BASE + 0x48)
#define RKVPSS2X_SCALE5_HC_OFFS_MI		(RKVPSS2X_SCALE5_BASE + 0x4c)
#define RKVPSS2X_SCALE5_IN_CROP_OFFSET		(RKVPSS2X_SCALE5_BASE + 0x50)
#define RKVPSS2X_SCALE5_CTRL_SHD		(RKVPSS2X_SCALE5_BASE + 0x80)
#define RKVPSS2X_SCALE5_SRC_SIZE_SHD		(RKVPSS2X_SCALE5_BASE + 0x88)
#define RKVPSS2X_SCALE5_DST_SIZE_SHD		(RKVPSS2X_SCALE5_BASE + 0x8c)
#define RKVPSS2X_SCALE5_HY_FAC_SHD		(RKVPSS2X_SCALE5_BASE + 0x90)
#define RKVPSS2X_SCALE5_HC_FAC_SHD		(RKVPSS2X_SCALE5_BASE + 0x94)
#define RKVPSS2X_SCALE5_VY_FAC_SHD		(RKVPSS2X_SCALE5_BASE + 0x98)
#define RKVPSS2X_SCALE5_VC_FAC_SHD		(RKVPSS2X_SCALE5_BASE + 0x9c)
#define RKVPSS2X_SCALE5_HY_OFFS_SHD		(RKVPSS2X_SCALE5_BASE + 0xa0)
#define RKVPSS2X_SCALE5_HC_OFFS_SHD		(RKVPSS2X_SCALE5_BASE + 0xa4)
#define RKVPSS2X_SCALE5_VY_OFFS_SHD		(RKVPSS2X_SCALE5_BASE + 0xa8)
#define RKVPSS2X_SCALE5_VC_OFFS_SHD		(RKVPSS2X_SCALE5_BASE + 0xac)
#define RKVPSS2X_SCALE5_HY_SIZE_SHD		(RKVPSS2X_SCALE5_BASE + 0xc0)
#define RKVPSS2X_SCALE5_HC_SIZE_SHD		(RKVPSS2X_SCALE5_BASE + 0xc4)
#define RKVPSS2X_SCALE5_HY_OFFS_MI_SHD		(RKVPSS2X_SCALE5_BASE + 0xc8)
#define RKVPSS2X_SCALE5_HC_OFFS_MI_SHD		(RKVPSS2X_SCALE5_BASE + 0xcc)
#define RKVPSS2X_SCALE5_IN_CROP_OFFSET_SHD	(RKVPSS2X_SCALE5_BASE + 0xd0)

/* ASPTO4 */
#define RKVPSS2X_RATIO4_BASE			0x0b00
#define RKVPSS2X_RATIO4_CTRL			(RKVPSS2X_RATIO4_BASE + 0x00)
#define RKVPSS2X_RATIO4_UPDATE			(RKVPSS2X_RATIO4_BASE + 0x04)
#define RKVPSS2X_RATIO4_ACT_SIZE		(RKVPSS2X_RATIO4_BASE + 0x10)
#define RKVPSS2X_RATIO4_VIR_SIZE		(RKVPSS2X_RATIO4_BASE + 0x14)
#define RKVPSS2X_RATIO4_OFFS			(RKVPSS2X_RATIO4_BASE + 0x18)
#define RKVPSS2X_RATIO4_COLOR			(RKVPSS2X_RATIO4_BASE + 0x1c)
#define RKVPSS2X_RATIO4_ACT_SIZE_SHD		(RKVPSS2X_RATIO4_BASE + 0x30)
#define RKVPSS2X_RATIO4_VIR_SIZE_SHD		(RKVPSS2X_RATIO4_BASE + 0x34)
#define	RKVPSS2X_RATIO4_OFFS_SHD		(RKVPSS2X_RATIO4_BASE + 0x38)
#define RKVPSS2X_RATIO4_COLOR_SHD		(RKVPSS2X_RATIO4_BASE + 0x3c)

/* ASPTO5 */
#define RKVPSS2X_RATIO5_BASE			0x0d00
#define RKVPSS2X_RATIO5_CTRL			(RKVPSS2X_RATIO5_BASE + 0x00)
#define RKVPSS2X_RATIO5_UPDATE			(RKVPSS2X_RATIO5_BASE + 0x04)
#define RKVPSS2X_RATIO5_ACT_SIZE		(RKVPSS2X_RATIO5_BASE + 0x10)
#define RKVPSS2X_RATIO5_VIR_SIZE		(RKVPSS2X_RATIO5_BASE + 0x14)
#define RKVPSS2X_RATIO5_OFFS			(RKVPSS2X_RATIO5_BASE + 0x18)
#define RKVPSS2X_RATIO5_COLOR			(RKVPSS2X_RATIO5_BASE + 0x1c)
#define RKVPSS2X_RATIO5_ACT_SIZE_SHD		(RKVPSS2X_RATIO5_BASE + 0x30)
#define RKVPSS2X_RATIO5_VIR_SIZE_SHD		(RKVPSS2X_RATIO5_BASE + 0x34)
#define RKVPSS2X_RATIO5_OFFS_SHD		(RKVPSS2X_RATIO5_BASE + 0x38)
#define RKVPSS2X_RATIO5_COLOR_SHD		(RKVPSS2X_RATIO5_BASE + 0x3c)

/* MI */
#define RKVPSS2X_MI_BASE			0x3000
#define RKVPSS2X_MI_WR_FBCE_CTRL		(RKVPSS2X_MI_BASE + 0x20)
#define RKVPSS2X_MI_WR_FBCE_SIZE		(RKVPSS2X_MI_BASE + 0x24)
#define RKVPSS2X_MI_WR_FBCE_OFFSET		(RKVPSS2X_MI_BASE + 0x28)
#define RKVPSS2X_MI_CHN0_WR_CB_STRIDE		(RKVPSS2X_MI_BASE + 0x240)
#define RKVPSS2X_MI_CHN0_WR_CB_PIC_SIZE		(RKVPSS2X_MI_BASE + 0x24c)
#define RKVPSS2X_MI_CHN0_WR_Y_STRIDE_SHD	(RKVPSS2X_MI_BASE + 0x26c)
#define RKVPSS2X_MI_CHN0_WR_CB_STRIDE_SHD	(RKVPSS2X_MI_BASE + 0x27c)
#define RKVPSS2X_MI_CHN1_WR_CB_STRIDE		(RKVPSS2X_MI_BASE + 0x340)
#define RKVPSS2X_MI_CHN1_WR_CB_PIC_SIZE		(RKVPSS2X_MI_BASE + 0x34c)
#define RKVPSS2X_MI_CHN1_WR_Y_STRIDE_SHD	(RKVPSS2X_MI_BASE + 0x36c)
#define RKVPSS2X_MI_CHN1_WR_CB_STRIDE_SHD	(RKVPSS2X_MI_BASE + 0x37c)
#define RKVPSS2X_MI_CHN2_WR_Y_STRIDE_SHD	(RKVPSS2X_MI_BASE + 0x46c)
#define RKVPSS2X_MI_CHN3_WR_Y_STRIDE_SHD	(RKVPSS2X_MI_BASE + 0x56c)
#define RKVPSS2X_MI_CHN4_WR_CTRL		(RKVPSS2X_MI_BASE + 0x600)
#define RKVPSS2X_MI_CHN4_WR_Y_BASE		(RKVPSS2X_MI_BASE + 0x610)
#define RKVPSS2X_MI_CHN4_WR_Y_SIZE		(RKVPSS2X_MI_BASE + 0x614)
#define RKVPSS2X_MI_CHN4_WR_Y_OFFS_CNT		(RKVPSS2X_MI_BASE + 0x618)
#define RKVPSS2X_MI_CHN4_WR_Y_OFFS_CNT_START	(RKVPSS2X_MI_BASE + 0x61c)
#define RKVPSS2X_MI_CHN4_WR_CB_BASE		(RKVPSS2X_MI_BASE + 0x620)
#define RKVPSS2X_MI_CHN4_WR_CB_SIZE		(RKVPSS2X_MI_BASE + 0x624)
#define RKVPSS2X_MI_CHN4_WR_CB_OFFS_CNT		(RKVPSS2X_MI_BASE + 0x628)
#define RKVPSS2X_MI_CHN4_WR_CB_OFFS_CNT_START	(RKVPSS2X_MI_BASE + 0x62c)
#define RKVPSS2X_MI_CHN4_WR_Y_STRIDE		(RKVPSS2X_MI_BASE + 0x630)
#define RKVPSS2X_MI_CHN4_WR_Y_PIC_WIDTH		(RKVPSS2X_MI_BASE + 0x634)
#define RKVPSS2X_MI_CHN4_WR_Y_PIC_SIZE		(RKVPSS2X_MI_BASE + 0x63c)
#define RKVPSS2X_MI_CHN4_WR_CTRL_SHD		(RKVPSS2X_MI_BASE + 0x650)
#define RKVPSS2X_MI_CHN4_WR_Y_BASE_SHD		(RKVPSS2X_MI_BASE + 0x660)
#define RKVPSS2X_MI_CHN4_WR_Y_SIZE_SHD		(RKVPSS2X_MI_BASE + 0x664)
#define RKVPSS2X_MI_CHN4_WR_Y_OFFS_CNT_SHD	(RKVPSS2X_MI_BASE + 0x668)
#define RKVPSS2X_MI_CHN4_WR_Y_STRDE_SHD		(RKVPSS2X_MI_BASE + 0x66c)
#define RKVPSS2X_MI_CHN4_WR_CB_BASE_SHD		(RKVPSS2X_MI_BASE + 0x670)
#define RKVPSS2X_MI_CHN4_WR_CB_SIZE_SHD		(RKVPSS2X_MI_BASE + 0x674)
#define RKVPSS2X_MI_CHN4_WR_CB_OFFS_CNT_SHD	(RKVPSS2X_MI_BASE + 0x678)
#define RKVPSS2X_MI_CHN4_WR_Y_END_ADDR		(RKVPSS2X_MI_BASE + 0x680)
#define RKVPSS2X_MI_CHN4_WR_CB_END_ADDR		(RKVPSS2X_MI_BASE + 0x684)
#define RKVPSS2X_MI_CHN4_WR_LINE_CNT		(RKVPSS2X_MI_BASE + 0x688)
#define RKVPSS2X_MI_CHN5_WR_CTRL		(RKVPSS2X_MI_BASE + 0x700)
#define RKVPSS2X_MI_CHN5_WR_Y_BASE		(RKVPSS2X_MI_BASE + 0x710)
#define RKVPSS2X_MI_CHN5_WR_Y_SIZE		(RKVPSS2X_MI_BASE + 0x714)
#define RKVPSS2X_MI_CHN5_WR_Y_OFFS_CNT		(RKVPSS2X_MI_BASE + 0x718)
#define RKVPSS2X_MI_CHN5_WR_Y_OFFS_CNT_START	(RKVPSS2X_MI_BASE + 0x71c)
#define RKVPSS2X_MI_CHN5_WR_CB_BASE		(RKVPSS2X_MI_BASE + 0x720)
#define RKVPSS2X_MI_CHN5_WR_CB_SIZE		(RKVPSS2X_MI_BASE + 0x724)
#define RKVPSS2X_MI_CHN5_WR_CB_OFFS_CNT		(RKVPSS2X_MI_BASE + 0x728)
#define RKVPSS2X_MI_CHN5_WR_CB_OFFS_CNT_START	(RKVPSS2X_MI_BASE + 0x72c)
#define RKVPSS2X_MI_CHN5_WR_Y_STRIDE		(RKVPSS2X_MI_BASE + 0x730)
#define RKVPSS2X_MI_CHN5_WR_Y_PIC_WIDTH		(RKVPSS2X_MI_BASE + 0x734)
#define RKVPSS2X_MI_CHN5_WR_Y_PIC_SIZE		(RKVPSS2X_MI_BASE + 0x73c)
#define RKVPSS2X_MI_CHN5_WR_CTRL_SHD		(RKVPSS2X_MI_BASE + 0x750)
#define RKVPSS2X_MI_CHN5_WR_Y_BASE_SHD		(RKVPSS2X_MI_BASE + 0x760)
#define RKVPSS2X_MI_CHN5_WR_Y_SIZE_SHD		(RKVPSS2X_MI_BASE + 0x764)
#define RKVPSS2X_MI_CHN5_WR_Y_OFFS_CNT_SHD	(RKVPSS2X_MI_BASE + 0x768)
#define RKVPSS2X_MI_CHN5_WR_Y_STRDE_SHD		(RKVPSS2X_MI_BASE + 0x76c)
#define RKVPSS2X_MI_CHN5_WR_CB_BASE_SHD		(RKVPSS2X_MI_BASE + 0x770)
#define RKVPSS2X_MI_CHN5_WR_CB_SIZE_SHD		(RKVPSS2X_MI_BASE + 0x774)
#define RKVPSS2X_MI_CHN5_WR_CB_OFFS_CNT_SHD	(RKVPSS2X_MI_BASE + 0x778)
#define RKVPSS2X_MI_CHN5_WR_Y_END_ADDR		(RKVPSS2X_MI_BASE + 0x780)
#define RKVPSS2X_MI_CHN5_WR_CB_END_ADDR		(RKVPSS2X_MI_BASE + 0x784)
#define RKVPSS2X_MI_CHN5_WR_LINE_CNT		(RKVPSS2X_MI_BASE + 0x788)

/********* BIT **********/

/* VPSS_CTRL */
#define RKVPSS2X_VPSS2ENC_PATH_EN		BIT(11)
#define RKVPSS2X_SENSOR_ID(x)			(((x) & 0x7) << 12)
#define RKVPSS2X_CHN4_CMSC_SEL(x)		(((x) & 0x3) << 16)
#define RKVPSS2X_CHN5_CMSC_SEL(x)		(((x) & 0x3) << 18)

/* VPSS_ONLINE */
#define RKVPSS2X_ISP2VPSS_CHN4_SEL(x)		(((x) & 0x3) << 8)
#define RKVPSS2X_ISP2VPSS_CHN5_SEL(x)		(((x) & 0x3) << 10)

/* VPSS_CLK_EN */
#define RKVPSS2X_SCL4_CLK_EN			BIT(12)
#define RKVPSS2X_SCL5_CLK_EN			BIT(13)
#define RKVPSS2X_RATIO4_CLK_EN			BIT(14)
#define RKVPSS2X_RATIO5_CLK_EN			BIT(15)

/* VPSS_CLK_GATE */
#define RKVPSS2X_SCL4_CKG_DIS			BIT(12)
#define RKVPSS2X_SCL5_CKG_DIS			BIT(13)
#define RKVPSS2X_RATIO4_CKG_DIS			BIT(14)
#define RKVPSS2X_RATI05_CKG_DIS			BIT(15)
#define RKVPSS2X_MI_CHN4_CKG_DIS		BIT(20)
#define RKVPSS2X_MI_CHN5_CKG_DIS		BIT(21)

/* VPSS_IMSC */
#define RKVPSS2X_SCL4_IN_FRM_END		BIT(16)
#define RKVPSS2X_SCL5_IN_FRM_END		BIT(17)
#define RKVPSS2X_RATIO4_IN_FRM_END		BIT(18)
#define RKVPSS2X_RATIO5_IN_FRM_END		BIT(19)

/* VPSS2ENC_DEBUG */
#define RKVPSS2X_RO_VPSS2ENC_LINE_CNT(x)	((x) & 0x3fff)
#define RKVPSS2X_RO_VPSS2ENC_FRM_CNT(x)		(((x) >> 16) & 0xff)


/* VPSS_CTRL_SHD  */
#define RKVPSS2X_VPSS2ENC_PATH_EN_SHD		BIT(11)

/* VPSS_ONLINE_SHD */
#define RKVPSS2X_CHN4_EN_SHD			BIT(8)
#define RKVPSS2X_ISP_CHN4_EN_SHD		BIT(9)
#define RKVPSS2X_CHN5_EN_SHD			BIT(10)
#define RKVPSS2X_ISP_CHN5_EN_SHD		BIT(11)
#define RKVPSS2X_ISP_USE_CMSC_EN_SHD		BIT(18)
#define RKVPSS2X_VPSS_USE_CMSC_EN_SHD		BIT(19)

/* VPSS_WORKING */
#define RKVPSS2X_SCL4_WORKING			BIT(12)
#define RKVPSS2X_SCL5_WORKING			BIT(13)
#define RKVPSS2X_RATIO4_WORKING			BIT(14)
#define	RKVPSS2X_RATIO5_WORKING			BIT(15)

/* CMSC_CTRL */
#define RKVPSS2X_CMSC_BLK_SIZE(x)		(((x) & 0x7) << 8)

/* CROP_CTRL_SHD */
#define RKVPSS2X_CROP_CHN4_EN_SHD		BIT(4)
#define RKVPSS2X_CROP_CHN5_EN_SHD		BIT(5)

/* CROP_CH4_5 */
#define RKVPSS2X_CROP_OFFS(v, h)		(((v & 0x3fff) << 16) | (h & 0x3fff))
#define RKVPSS2X_CROP_SIZE(v, h)		(((v & 0x3fff) << 16) | (h & 0x3fff))


/* SCALE_CTRL */
#define RKVPSS2X_SW_AVG_SCALE_H_EN		BIT(8)
#define RKVPSS2X_SW_AVG_SCALE_V_EN		BIT(9)

/* MI_FORCE_UPDATE */
#define	RKVPSS2X_MI_CHN4_FORCE_UPD		BIT(8)
#define RKVPSS2X_MI_CHN5_FORCE_UPD		BIT(9)

/* MI_WR_FBCE_SET */
#define RKVPSS2X_MI_WR_FBCE_SEL(x)		(BIT(0) << (x))
#define	RKVPSS2X_WR_FBCE_FORCE_UN_EN		BIT(2)
#define RKVPSS2X_WR_FBCE_PAYL_ALIGN_EN		BIT(3)
#define RKVPSS2X_MI_WR_FBCE_SET_SHD(x)		(BIT(28) << (x))

/* MI_IMSC */
#define RKVPSS2X_MI_CHN4_FRM_END		BIT(16)
#define RKVPSS2X_MI_CHN5_FRM_END		BIT(17)
#define RKVPSS2X_MI_RD_FBCD_ERR			BIT(29)

/* MI_RD_CTRL */
#define RKVPSS2X_MI_RD_INPUT_UYVY	3

/* MI_CHN1_WR_CTRL */
#define RKVPSS2X_CH1_WR_RGB888_ALPHA(x)	((x & 0xff) << 16)

/* MI_WR_FBCE_CTRL */
#define RKVPSS2X_SW_MI_WR_FBCE_SEL(x)	((x) & 0x3)

/* MI_WR_FBCE_SIZE */
#define RKVPSS2X_SW_WR_FBCE_SIZE(w, h)	((w & 0x7fff) | (h & 0x7fff) << 16)
#endif

