obj-$(CONFIG_AM_VOUT) += vout_notify.o vout_serve.o vinfo.o vdac_dev.o

obj-$(CONFIG_AM_TV_OUTPUT) += tv_vout.o tv_out_reg.o enc_clk_config.o

obj-$(CONFIG_AML_WSS)	+= wss.o

ccflags-y += -Idrivers/amlogic/display/
