# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_VIDEO_MAXIM_DES_MAXIM2C)	+= maxim2c.o
maxim2c-objs	+= maxim2c_i2c.o \
		   maxim2c_mipi_txphy.o \
		   maxim2c_video_pipe.o \
		   maxim2c_link.o \
		   maxim2c_remote.o \
		   maxim2c_pattern.o \
		   maxim2c_v4l2.o \
		   maxim2c_drv.o
