
obj-$(CONFIG_AML_NEXT_GEN_NAND)	+= amlnf_phy.o
amlnf_phy-objs =
amlnf_phy-objs += chip.o
amlnf_phy-objs  += chip_operation.o
amlnf_phy-objs  += chipenv.o
amlnf_phy-objs  += amlnand_init.o
amlnf_phy-objs  += hw_controller.o
amlnf_phy-objs  += id_table.o
amlnf_phy-objs  += new_nand.o
amlnf_phy-objs  += boot_operation.o

