obj-m	+=	media_clock.o
media_clock-objs += ../chips/chips.o
media_clock-objs += clk/clkg12.o
media_clock-objs += clk/clk.o
media_clock-objs += switch/amports_gate.o
media_clock-objs += ../chips/decoder_cpu_ver_info.o
