##########################################
########## Amlogic codec memory manager ###############
##########################################

##########################################
## The order of directories matter.
## Do not change.
##########################################


obj-$(CONFIG_AML_CODEC_MM)	+= codec_mm.o codec_mm_scatter.o
obj-$(CONFIG_AML_CODEC_MM)	+= codec_mm_keeper.o

