# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_VIDEO_MAXIM_SER_MAX9295)	+= max9295.o
obj-$(CONFIG_VIDEO_MAXIM_SER_MAX96715)	+= max96715.o
obj-$(CONFIG_VIDEO_MAXIM_SER_MAX96717)	+= max96717.o

maxim-dummy-objs := dummy.o
maxim-sc320at-objs := sc320at.o
maxim-ox01f10-objs := ox01f10.o
maxim-ov231x-objs := ov231x.o
maxim-ox03j10-objs := ox03j10.o
maxim-os04a10-objs := os04a10.o

obj-$(CONFIG_VIDEO_MAXIM_CAM_DUMMY)	+= maxim-dummy.o
obj-$(CONFIG_VIDEO_MAXIM_CAM_SC320AT)	+= maxim-sc320at.o
obj-$(CONFIG_VIDEO_MAXIM_CAM_OX01F10)	+= maxim-ox01f10.o
obj-$(CONFIG_VIDEO_MAXIM_CAM_OV231X)	+= maxim-ov231x.o
obj-$(CONFIG_VIDEO_MAXIM_CAM_OX03J10)	+= maxim-ox03j10.o
obj-$(CONFIG_VIDEO_MAXIM_CAM_OS04A10)	+= maxim-os04a10.o
