obj-$(CONFIG_AMLOGIC_CRYPTO_DMA) 				+= aml-cryp-dma.o
aml-cryp-dma-objs:= aml-dma.o aml-crypto-dma.o
obj-$(CONFIG_AMLOGIC_CRYPTO_DMA) 				+= aml-aes-dma.o
obj-$(CONFIG_AMLOGIC_CRYPTO_DMA) 				+= aml-tdes-dma.o
obj-$(CONFIG_AMLOGIC_CRYPTO_DMA) 				+= aml-sha-dma.o
