MODULE_NAME = aml_crypto_dma

obj-$(CONFIG_AMLOGIC_CRYPTO_DMA) += $(MODULE_NAME).o
$(MODULE_NAME)-objs = aml-dma.o aml-crypto-dma.o aml-aes-dma.o aml-tdes-dma.o aml-sha-dma.o aml-crypto-device.o aml-sm4-dma.o
