obj-m	+=	decoder_common.o
decoder_common-objs	+=	utils.o vdec.o vdec_input.o amvdec.o
decoder_common-objs	+=	decoder_mmu_box.o decoder_bmmu_box.o
decoder_common-objs	+=	config_parser.o vdec_profile.o
decoder_common-objs	+=	amstream_profile.o
decoder_common-objs	+=	frame_check.o amlogic_fbc_hook.o
decoder_common-objs	+=	vdec_v4l2_buffer_ops.o
decoder_common-objs	+=	vdec_sync.o
decoder_common-objs	+=	vdec_power_ctrl.o
decoder_common-objs	+=	vdec_canvas_utils.o
decoder_common-objs	+=	vdec_feature.o
decoder_common-objs	+=	decoder_dma_alloc.o
decoder_common-objs	+=	vdec_ge2d_utils.o

