#
# Makefile for the linux kernel.
#

# Common support
# Board support
obj-$(CONFIG_ARCH_MESON)	+= meson.o
obj-$(CONFIG_AMLOGIC_USB) += usbclock.o

# Cache config
obj-$(CONFIG_CACHE_L2X0) += cache.o

