include drivers/amlogic/media/vout/vout_serve/Makefile

include drivers/amlogic/media/vout/hdmitx/Makefile

include drivers/amlogic/media/vout/cvbs/Makefile

include drivers/amlogic/media/vout/vdac/Makefile

include drivers/amlogic/media/vout/lcd/Makefile
