include drivers/amlogic/media/vout/vclk_serve/Makefile

include drivers/amlogic/media/vout/vout_serve/Makefile

include drivers/amlogic/media/vout/hdmitx21/Makefile

include drivers/amlogic/media/vout/hdmitx/Makefile

include drivers/amlogic/media/vout/cvbs/Makefile

include drivers/amlogic/media/vout/vdac/Makefile

include drivers/amlogic/media/vout/lcd/Makefile

include drivers/amlogic/media/vout/peripheral_lcd/Makefile

include drivers/amlogic/media/vout/dsc/Makefile

