# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the focaltech touchscreen drivers.
#

# Makefile for the focaltech touchscreen drivers.

obj-$(CONFIG_TOUCHSCREEN_FT5726) += focaltech_ft5762.o
focaltech_ft5762-y	+=  focaltech_core.o
focaltech_ft5762-y	+=  focaltech_ex_fun.o
focaltech_ft5762-y	+=  focaltech_ex_mode.o
focaltech_ft5762-y	+=  focaltech_gesture.o
focaltech_ft5762-y	+=  focaltech_esdcheck.o
focaltech_ft5762-y	+=  focaltech_point_report_check.o
focaltech_ft5762-y	+=  focaltech_i2c.o
focaltech_ft5762-y	+=  focaltech_flash.o
focaltech_ft5762-y	+=  focaltech_flash/focaltech_upgrade_ft5726_003.o
