#
# Makefile for the DVB driver.
#
obj-y +=amlci.o

amlci-objs = aml_pcmcia.o aml_spi.o aml_ci.o
ccflags-y += -I$(srctree)/drivers/amlogic/dvb_tv/amlci
ccflags-y += -I$(srctree)/drivers/amlogic/dvb_tv/
ccflags-y += -I$(srctree)/

