obj-m	+= aml_hardware_fe.o

ccflags-y += -I$(srctree)/drivers/media/dvb-core -I$(srctree)/drivers/gpio -I$(srctree)/include

aml_hardware_fe-objs += aml_fe.o

# aml_atvdemod-objs += atv_demod/atvdemod_frontend.o
# aml_atvdemod-objs += atv_demod/atvdemod_func.o

# aml_dtvdemod-objs += dtv_demod/aml_demod.o
# aml_dtvdemod-objs += dtv_demod/amlfrontend.o
# aml_dtvdemod-objs += dtv_demod/demod_func.o
# aml_dtvdemod-objs += dtv_demod/dvbc_func.o
# aml_dtvdemod-objs += dtv_demod/dvbt_func.o
# aml_dtvdemod-objs += dtv_demod/i2c_func.o
# aml_dtvdemod-objs += dtv_demod/tuner_func.o
