# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_VIDEO_MAXIM_DES_MAXIM4C)	+= maxim4c.o
maxim4c-objs	+= maxim4c_i2c.o \
		   maxim4c_mipi_txphy.o \
		   maxim4c_video_pipe.o \
		   maxim4c_link.o \
		   maxim4c_remote.o \
		   maxim4c_pattern.o \
		   maxim4c_v4l2.o \
		   maxim4c_drv.o \
		   maxim4c_debugfs.o
