#
# Makefile for Tvin.
#

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_TVIN) += vin/tvin/tvin_format_table.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_TVIN) += vin/tvin/tvin_frontend.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_TVIN) += vin/tvin/tvin_global.o

include drivers/amlogic/media/vin/tvin/vdin/Makefile

include drivers/amlogic/media/vin/tvin/vdin/Makefile

include drivers/amlogic/media/vin/tvin/bt656/Makefile
