# SPDX-License-Identifier: GPL-2.0-or-later

obj-$(CONFIG_TOUCHSCREEN_CHIPONE_9551R) += chipone-ts.o
chipone-ts-y += cts_driver.o
chipone-ts-y += cts_core.o
chipone-ts-y += cts_sfctrlv2.o
chipone-ts-y += cts_spi_flash.o
chipone-ts-y += cts_firmware.o
chipone-ts-y += cts_test.o
chipone-ts-y += cts_charger_detect.o
chipone-ts-y += cts_earjack_detect.o
chipone-ts-y += cts_tcs.o
chipone-ts-y += cts_platform.o
chipone-ts-y += cts_tool.o
chipone-ts-y += cts_sysfs.o
chipone-ts-y += cts_strerror.o
chipone-ts-y += cts_oem.o
