obj-m	+=	 stream_input.o

stream_input-objs	+=	amports/amstream.o
stream_input-objs	+=	amports/adec.o
stream_input-objs	+=	parser/thread_rw.o
stream_input-objs	+=	parser/streambuf.o
stream_input-objs	+=	parser/esparser.o
stream_input-objs	+=	parser/tsdemux.o
stream_input-objs	+=	parser/psparser.o
stream_input-objs	+=	parser/rmparser.o
stream_input-objs	+=	subtitle/subtitle.o

obj-$(CONFIG_AMLOGIC_DVB)   += parser/hw_demux/
#obj-y 	+= 	tv_frontend/
# obj-y	+=	box-frontend/avl6211/
# obj-y	+=	box-frontend/atbm8881/
# obj-y	+=	box-frontend/avl68xx/
