obj-$(CONFIG_AMLOGIC_POWER)		+= power_ctrl.o
obj-$(CONFIG_AMLOGIC_POWER)		+= sec_pwr_ctrl.o
obj-$(CONFIG_AMLOGIC_POWER)		+= a1_power_domain.o
obj-$(CONFIG_AMLOGIC_POWER)		+= c1_power_domain.o
obj-$(CONFIG_AMLOGIC_POWER)		+= power_domain_sysfs.o
obj-$(CONFIG_AMLOGIC_POWER_SUPPLY)	+= supply/
