MODULE_NAME = aml_power

obj-$(CONFIG_AMLOGIC_POWER)		+= $(MODULE_NAME).o
$(MODULE_NAME)-y += power_ctrl.o sec_pwr_ctrl.o sec_power_domain.o power_domain_sysfs.o

obj-$(CONFIG_AMLOGIC_POWER_SUPPLY)	+= supply/
