#
# Amlogic external hdmi-in chips Makefile
#

obj-$(CONFIG_TVIN_HDMI_EXT) += hdmiin.o

hdmiin-objs := hdmiin_drv.o hdmiin_attrs.o platform_iface.o hdmiin_hw_iface.o vdin_iface.o

obj-$(CONFIG_TVIN_HDMI_EXT_SII9135) += hw_sii9135/
