# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2024 Rockchip Electronics Co., Ltd.

obj-$(CONFIG_ROCKCHIP_FLEXBUS_CIF) += flexbus_cif.o
flexbus_cif-objs += dev.o \
		    capture.o \
		    procfs.o \
		    common.o
