$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_LUT_DMA)	+=	common/lut_dma/lut_dma_mgr.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_LUT_DMA)	+=	common/lut_dma/lut_dma_io.o

ccflags-y += -Iinclude/linux/amlogic/media/lut_dma/
