##########################################
########## Amlogic codec memory manager ###############
##########################################

##########################################
## The order of directories matter.
## Do not change.
##########################################


obj-$(CONFIG_AML_CODEC_MM)	+= configs.o configs_module.o
obj-$(CONFIG_AML_CODEC_MM)	+= configs_test.o


