#
# aml_nftl
#
#EXTRA_CFLAGS += -Idrivers/amlogic/nand/aml_nftl_new/nftl


obj-$(CONFIG_AML_NFTL_NEW)	+=   aml_nftl_core.o
aml_nftl_core-objs  += aml_nftl_list.o
aml_nftl_core-objs  += aml_nftl_logic.o
aml_nftl_core-objs  += aml_nftl_gc.o
aml_nftl_core-objs  += aml_nftl_cache.o
aml_nftl_core-objs  += aml_nftl_common.o
aml_nftl_core-objs  += aml_nftl_create_list.o
aml_nftl_core-objs  += aml_nftl_start.o
aml_nftl_core-objs  += aml_nftl_interface.o
aml_nftl_core-objs  += aml_nftl_tbl_trans.o


