# SPDX-License-Identifier: (GPL-2.0+ OR MIT)

asflags-y += -mfloat-abi=softfp -mfpu=neon

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_DI_PROCESS) += video_processor/di_process/di_proc_file.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_DI_PROCESS) += video_processor/di_process/di_proc_buf_mgr.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_DI_PROCESS) += video_processor/di_process/di_process.o
