#drivers/input/touchscreen
#
#Makefile for the touch driver of Focaltech
#
	
	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_core.o
	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_platform_data.o
	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_report.o
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_esd_protection.o
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_gesture.o
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_proximity.o
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_apk_node.o
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_sysfs.o
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_flash/
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_global/
#	obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_ALL) += focaltech_test/
