$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_COMMON) += common/arch/registers/register_map.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_COMMON) += common/arch/registers/register_ops.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_COMMON) += common/arch/registers/register_ops_m8.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_COMMON) += common/arch/registers/cpu_version.o
