
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BL_EXTERN) += vout/lcd/backlight/bl_extern/bl_extern.o vout/lcd/backlight/bl_extern/bl_extern_i2c.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BL_EXTERN_I2C_LP8556) += vout/lcd/backlight/bl_extern/i2c_lp8556.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BL_EXTERN_MIPI_LT070ME05) += vout/lcd/backlight/bl_extern/mipi_lt070me05.o

