MEDIA_MODULE_NAME = aml_media
obj-$(CONFIG_AMLOGIC_MEDIA_MODULE) = $(MEDIA_MODULE_NAME).o
$(MEDIA_MODULE_NAME)-y = media_main.o

include drivers/amlogic/media/common/Makefile

include drivers/amlogic/media/video_sink/Makefile

include drivers/amlogic/media/osd/Makefile

include drivers/amlogic/media/vout/Makefile

include drivers/amlogic/media/deinterlace/Makefile

include drivers/amlogic/media/di_multi/Makefile

include drivers/amlogic/media/di_local/Makefile

include drivers/amlogic/media/video_processor/Makefile

include drivers/amlogic/media/enhancement/Makefile

include drivers/amlogic/media/frame_sync/Makefile

include drivers/amlogic/media/gdc/Makefile

include drivers/amlogic/media/vin/Makefile
