$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TABLET) += vout/lcd/lcd_tablet/lcd_tablet.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TABLET) += vout/lcd/lcd_tablet/lcd_drv.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TABLET) += vout/lcd/lcd_tablet/mipi_dsi_util.o

include drivers/amlogic/media/vout/lcd/lcd_tablet/DisplayPort/Makefile
