MODULE_NAME = aml_usb2phy
obj-$(CONFIG_AMLOGIC_USBPHY)      += $(MODULE_NAME).o
$(MODULE_NAME)-y += phy-aml-new-usb-v2.o
$(MODULE_NAME)-y += phy-aml-new-usb2-v2.o
$(MODULE_NAME)-y += phy-aml-new-usb.o
$(MODULE_NAME)-y += phy-aml-new-usb2.o
