##########################################
########## Amlogic Drivers ###############
##########################################

##########################################
## The order of directories matter.
## Do not change.
##########################################


obj-y	+=clocksource/

obj-y	+=uart/

obj-y	+=cpu_version/

obj-y	+=gpio/

obj-y	+=pinctrl/

obj-y	+=clk/

obj-y 	+=rtc/

obj-y	+=i2c/

obj-y	+=iomap/

obj-y	+=aml_debug/
