
##########################################
########## Amlogic Drivers ###############
##########################################
obj-$(CONFIG_AMLOGIC_CPU_HOTPLUG)	+= cpu_hotplug/
obj-$(CONFIG_AMLOGIC_CPU_VERSION)	+= cpu_version/
obj-$(CONFIG_AMLOGIC_EFUSE)             += efuse/
obj-$(CONFIG_AMLOGIC_DEFENDKEY)		+= defendkey/
obj-$(CONFIG_AMLOGIC_MEDIA_ENABLE)	+= media/
obj-$(CONFIG_AMLOGIC_POWER)		+= power/
