
##########################################
########## Amlogic Drivers ###############
##########################################
obj-$(CONFIG_AMLOGIC_CPUIDLE)		+= cpuidle/
obj-$(CONFIG_CPU_FREQ)			+= cpufreq/
obj-$(CONFIG_MMC_MESON_GX)		+= mmc/
obj-$(CONFIG_AMLOGIC_EFUSE_UNIFYKEY)    += efuse_unifykey/
obj-$(CONFIG_AMLOGIC_DEFENDKEY)		+= defendkey/
obj-$(CONFIG_AMLOGIC_DDR_TOOL)		+= ddr_tool/
obj-$(CONFIG_AMLOGIC_CRYPTO_DMA)	+= crypto/
obj-$(CONFIG_AMLOGIC_AUTO_CAPTURE)	+= free_reserved/
obj-$(CONFIG_AMLOGIC_MHU_MBOX)		+= mailbox/
obj-$(CONFIG_AMLOGIC_REG_ACCESS)	+= reg_access/
obj-$(CONFIG_AMLOGIC_SUSPEND)		+= pm/
obj-$(CONFIG_AMLOGIC_PCIE)		+= pci/
obj-$(CONFIG_AMLOGIC_MEDIA_ENABLE)	+= media/
obj-$(CONFIG_AMLOGIC_POWER)		+= power/
obj-$(CONFIG_AMLOGIC_PINCTRL)		+= pinctrl/
obj-$(CONFIG_AMLOGIC_USB)               += usb/
obj-$(CONFIG_AMLOGIC_THERMAL)		+= thermal/
obj-$(CONFIG_AMLOGIC_CLK_DEBUG)		+= clk_debug/
obj-$(CONFIG_AMLOGIC_INPUT)		+= input/
obj-$(CONFIG_AMLOGIC_DEBUG)		+= debug/
obj-$(CONFIG_PWM_MESON)			+= pwm/
obj-$(CONFIG_AMLOGIC_TEE)		+= tee/
obj-$(CONFIG_AMLOGIC_MEMORY_EXTEND)	+= memory_ext/
obj-$(CONFIG_AMLOGIC_WIFI)      += wifi/
obj-$(CONFIG_AMLOGIC_JTAG_MESON)	+= jtag/
obj-$(CONFIG_AMLOGIC_UART)              += uart/
obj-$(CONFIG_AMLOGIC_BT_DEVICE) += bluetooth/
obj-$(CONFIG_AMLOGIC_GX_REBOOT)		+= reboot/
obj-$(CONFIG_AMLOGIC_SMARTCARD)		+= smartcard/
obj-$(CONFIG_AMLOGIC_GKI_TOOL)		+= gki_tool/
