# SPDX-License-Identifier: GPL-2.0
dtb-y += sm1_s905x3_ac213.dtb
dtb-y += sm1_s905x3_ac214.dtb
dtb-y += meson-a1-ad401.dtb
dtb-y += tm2_t962e2_ab311.dtb
dtb-y += t7_pxp.dtb
dtb-y += sc2_s905x4_ah212.dtb
dtb-y += sc2_s905x4_ah219.dtb
