dtb-$(CONFIG_ARM64) += kvim_linux.dtb
dtb-$(CONFIG_ARM64) += kvim2_linux.dtb
dtb-$(CONFIG_ARM64) += kvim3l_linux.dtb
dtb-$(CONFIG_ARM64) += kvim3_linux.dtb
dtb-$(CONFIG_ARM64) += riftone.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
