obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
obj-$(CONFIG_CHARGER_BQ25700)   += bq25700_charger.o
obj-$(CONFIG_BATTERY_CW2015)    += cw2015_battery.o
