#
# Makefile for amlogic uvm
#

ccflags-y += -Idrivers/staging/android/ -Idrivers/amlogic/

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_UVM_ALLOCATOR)		+= common/uvm/meson_uvm_allocator.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_UVM_CORE)			+= common/uvm/meson_uvm_core.o
