#
# aml_ntd
#
#EXTRA_CFLAGS += -Idrivers/amlogic/nand/aml_nftl_new/ntd


obj-$(CONFIG_AML_NEXT_GEN_NAND)	+=   aml_ntd.o
aml_ntd-objs +=  aml_ntd_blkdevs.o
aml_ntd-objs  += aml_ntdcore.o
aml_ntd-objs  += aml_ntdpart.o
#aml_ntd-objs  += aml_ntd_test.o
