#
# Makefile for LED
#

obj-$(CONFIG_AML_LED_SYS) += led_sys.o
obj-$(CONFIG_AML_LED_PWM) += led_pwm.o

obj-$(CONFIG_AML_LED_TRIGGER_BREATHE) += led_trigger_breathe.o
obj-$(CONFIG_AML_LED_TRIGGER_SCPI) += led_trigger_scpi.o
obj-$(CONFIG_AML_LED_TRIGGER_SCPISTOP) += led_trigger_scpistop.o
obj-$(CONFIG_AML_LED_TRIGGER_DISTURB) += led_trigger_disturb.o

