#
# Makefile for LED
#

obj-$(CONFIG_AML_LED_SYS) += aml_led_sys.o
obj-$(CONFIG_AML_LED_PWM) += aml_led_pwm.o

obj-$(CONFIG_AML_LED_TRIGGER_BREATHE) += aml_led_trigger_breathe.o
obj-$(CONFIG_AML_LED_TRIGGER_SCPI) += aml_led_trigger_scpi.o
obj-$(CONFIG_AML_LED_TRIGGER_SCPISTOP) += aml_led_trigger_scpistop.o

