$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_FB) += osd/osd_hw.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_FB) += osd/osd_fb.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_FB) += osd/osd_debug.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_FB) += osd/osd_backup.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_FB) += osd/osd_logo.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_FB) += osd/osd_io.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_FB) += osd/osd_antiflicker.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_FB) += osd/osd_clone.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_FB) += osd/osd_drm.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_FB) += osd/osd_rdma.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_FB) += osd/osd_virtual.o

$(MEDIA_MODULE_NAME)-$(CONFIG_INSTABOOT) += osd/osd_progressbar.o

ccflags-y += -I$(srctree)/drivers/amlogic/media/common/ion_dev/
ccflags-y += -I$(srctree)/drivers/staging/android/
