# SPDX-License-Identifier: GPL-2.0-or-later

obj-$(CONFIG_INV_ICM42670) += inv-icm42670.o
inv-icm42670-y += inv_icm42670_core.o
inv-icm42670-y += inv_icm42670_ring.o
inv-icm42670-y += inv_icm42670_trigger.o

obj-$(CONFIG_INV_ICM42670_I2C) += inv-icm42670-i2c.o
inv-icm42670-i2c-y += inv_icm42670_i2c.o

obj-$(CONFIG_INV_ICM42670_SPI) += inv-icm42670-spi.o
inv-icm42670-spi-y += inv_icm42670_spi.o
