asflags-y +=-mfloat-abi=softfp -mfpu=neon
ccflags-y += -Idrivers/staging/android/ion

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_IONVIDEO) += video_processor/ionvideo/ionvideo.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_IONVIDEO) += video_processor/ionvideo/ppmgr2.o
