#
# Makefile for LDIM.
#
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LOCAL_DIMMING) += vout/lcd/backlight/aml_ldim/ldim_dev_drv.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LOCAL_DIMMING) += vout/lcd/backlight/aml_ldim/ldim_spi.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LOCAL_DIMMING) += vout/lcd/backlight/aml_ldim/ob3350_bl.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LOCAL_DIMMING) += vout/lcd/backlight/aml_ldim/global_bl.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LOCAL_DIMMING) += vout/lcd/backlight/aml_ldim/iw7027_bl.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LOCAL_DIMMING) += vout/lcd/backlight/aml_ldim/ldim_drv.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LOCAL_DIMMING) += vout/lcd/backlight/aml_ldim/ldim_func.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LOCAL_DIMMING) += vout/lcd/backlight/aml_ldim/ldim_hw.o
