# SPDX-License-Identifier: GPL-2.0

ccflags-$(CONFIG_GSENSOR_DEVICE) := -w

# sensor drivers
obj-$(CONFIG_GSENSOR_DEVICE)			+= accel/

obj-$(CONFIG_SENSOR_DEVICE)				+= sensor-i2c.o
obj-$(CONFIG_SENSOR_DEVICE)				+= sensor-dev.o
