# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_AML_TEE) += tee.o
tee-objs += tee_core.o
tee-objs += tee_shm.o
tee-objs += tee_shm_pool.o
tee-objs += tee_data_pipe.o
obj-$(CONFIG_AML_OPTEE) += optee/
