include drivers/amlogic/media/video_processor/ppmgr/Makefile

include drivers/amlogic/media/video_processor/utils/Makefile

include drivers/amlogic/media/video_processor/videosync/Makefile

include drivers/amlogic/media/video_processor/pic_dev/Makefile

include drivers/amlogic/media/video_processor/video_dev/Makefile

include drivers/amlogic/media/video_processor/ionvideo/Makefile

include drivers/amlogic/media/video_processor/v4lvideo/Makefile

include drivers/amlogic/media/video_processor/video_composer/Makefile
