obj-$(CONFIG_AMLOGIC_POST_PROCESS_MANAGER) += ppmgr/
obj-$(CONFIG_AMLOGIC_MEDIA_UTILS) += utils/
obj-$(CONFIG_AMLOGIC_VIDEOSYNC) += videosync/
obj-$(CONFIG_AMLOGIC_PIC_DEC) += pic_dev/
obj-$(CONFIG_AMLOGIC_V4L_VIDEO2) += video_dev/
obj-$(CONFIG_AMLOGIC_IONVIDEO)	+= ionvideo/
obj-$(CONFIG_AMLOGIC_V4L_VIDEO3)	+= v4lvideo/
obj-$(CONFIG_AMLOGIC_VIDEO_COMPOSER)	+= video_composer/
