#
# Makefile for TVAFE.
#
obj-$(CONFIG_TVIN_AFE) += tvin_afe.o
tvin_afe-objs := tvafe_adc.o tvafe_cvd.o tvafe_general.o tvafe.o

obj-$(CONFIG_TVIN_VBI) += tvin_vbi.o
obj-$(CONFIG_TVIN_AVIN_DETECT) += tvin_avin_detect.o
tvin_avin_detect-objs := tvafe_avin_detect.o
