#
# Makefile for LDIM.
#
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BL_LDIM) += vout/lcd/backlight/bl_ldim/ldim_drv.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BL_LDIM) += vout/lcd/backlight/bl_ldim/ldim_fw_param.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BL_LDIM) += vout/lcd/backlight/bl_ldim/ldim_debug.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BL_LDIM) += vout/lcd/backlight/bl_ldim/ldim_mem.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BL_LDIM) += vout/lcd/backlight/bl_ldim/ldim_reg.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BL_LDIM) += vout/lcd/backlight/bl_ldim/ldim_dev_drv.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BL_LDIM) += vout/lcd/backlight/bl_ldim/ldim_spi.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BL_LDIM) += vout/lcd/backlight/bl_ldim/global_bl.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BL_LDIM_OB3350) += vout/lcd/backlight/bl_ldim/ob3350_bl.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BL_LDIM_IW7038) += vout/lcd/backlight/bl_ldim/iw7038_bl.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BL_LDIM_IW7027) += vout/lcd/backlight/bl_ldim/iw7027_bl.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BL_LDIM_BLMCU) += vout/lcd/backlight/bl_ldim/mcu_bl.o
