#
# Makefile for LDIM.
#
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BL_LDIM) += vout/lcd/backlight/bl_ldim/ldim_drv.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BL_LDIM) += vout/lcd/backlight/bl_ldim/ldim_func.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BL_LDIM) += vout/lcd/backlight/bl_ldim/ldim_hw.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BL_LDIM) += vout/lcd/backlight/bl_ldim/ldim_debug.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BL_LDIM) += vout/lcd/backlight/bl_ldim/ldim_dev_drv.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BL_LDIM) += vout/lcd/backlight/bl_ldim/ldim_spi.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BL_LDIM) += vout/lcd/backlight/bl_ldim/ob3350_bl.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_BL_LDIM) += vout/lcd/backlight/bl_ldim/global_bl.o
