#Ascending by module name's ASCII
include drivers/amlogic/media/common/arch/Makefile

include drivers/amlogic/media/common/canvas/Makefile

include drivers/amlogic/media/common/ge2d/Makefile

include drivers/amlogic/media/common/ion_dev/Makefile

include drivers/amlogic/media/common/vpu/Makefile

include drivers/amlogic/media/common/rdma/Makefile

include drivers/amlogic/media/common/codec_mm/Makefile

include drivers/amlogic/media/common/vfm/Makefile

include drivers/amlogic/media/common/v4l_util/Makefile
