ccflags-y += -I$(srctree)/drivers/amlogic/media/osd/
ccflags-y += -I$(srctree)/drivers/staging/android
ccflags-y += -I$(srctree)/drivers/amlogic/media/common/ion_dev/

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_GE2D) += common/ge2d/bitblt.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_GE2D) += common/ge2d/fillrect.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_GE2D) += common/ge2d/ge2d_hw.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_GE2D) += common/ge2d/ge2dgen.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_GE2D) += common/ge2d/ge2d_wq.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_GE2D) += common/ge2d/stretchblt.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_GE2D) += common/ge2d/ge2d_main.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_GE2D) += common/ge2d/blend.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_GE2D) += common/ge2d/ge2d_dmabuf.o
