dtbo-y += uart3.dtbo \
		  pwm_f.dtbo \
		  i2c3.dtbo \
		  spi1.dtbo \
		  onewire.dtbo \
		  os08a10.dtbo \
		  disable-ts050.dtbo \
		  m2x-eth.dtbo \
		  otg-device.dtbo \
		  watchdog.dtbo \
		  i2s.dtbo \
		  can.dtbo \
		  mpu6050-i2c.dtbo \
		  ext_board.dtbo \
		  spdifin.dtbo

targets += $(dtbo-y)
always  := $(dtbo-y)
