#
# Amlogic Clock specific Makefile
#


obj-$(CONFIG_AMLOGIC_CLK) += clk.o clk-pll.o clk_measure.o \
                             clk-meson8m2.o hdmi-clk.o rstc.o \
                             clk_sys.o gp0_pll.o clk_mpll_clock.o \
                             clk-gxbb.o clk-gxtvbb.o \
                             clk-gxl.o clk-txl.o \
                             gpu_clk.o gxbb_hdmi_clk.o gxtvbb_hdmi_clk.o \
                             gp0_pll_gxl.o
