#
# Makefile for amprime_sl
#

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_ENHANCEMENT_PRIME_SL) += enhancement/amprime_sl/amprime_sl.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_ENHANCEMENT_PRIME_SL) += enhancement/amprime_sl/amprime_sl_hw.o


