#ifndef RDMA_REGS_HEADER_
#define RDMA_REGS_HEADER_

#define RDMA_AHB_START_ADDR_MAN 0x1cf0
#define RDMA_AHB_END_ADDR_MAN 0x1cf1
#define RDMA_AHB_START_ADDR_1 0x1cf2
#define RDMA_AHB_END_ADDR_1 0x1cf3
#define RDMA_AHB_START_ADDR_2 0x1cf4
#define RDMA_AHB_END_ADDR_2 0x1cf5
#define RDMA_AHB_START_ADDR_3 0x1cf6
#define RDMA_AHB_END_ADDR_3 0x1cf7
#define RDMA_ACCESS_AUTO 0x1cf8
#define RDMA_ACCESS_MAN 0x1cf9
#define RDMA_CTRL 0x1cfa
#define RDMA_STATUS 0x1cfb

#endif

