obj-$(CONFIG_AMLOGIC_USBPHY)		+= usbphy.o
obj-$(CONFIG_AMLOGIC_USBPHY)            += phy-aml-new-usb-v2.o
obj-$(CONFIG_AMLOGIC_USB2PHY)           += phy-aml-new-usb2-v2.o
obj-$(CONFIG_AMLOGIC_USB3PHY)           += phy-aml-new-usb3-v2.o
