ccflags-y += -I$(srctree)/drivers/amlogic/media/osd/
ccflags-y += -I$(srctree)/drivers/staging/android

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_VICP) += common/vicp/vicp_main.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_VICP) += common/vicp/vicp_reg.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_VICP) += common/vicp/vicp_log.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_VICP) += common/vicp/vicp_process.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_VICP) += common/vicp/vicp_rdma.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_VICP) += common/vicp/vicp_hardware.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_VICP) += common/vicp/vicp_hdr.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_VICP) += common/vicp/vicp_test.o
