$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_PERIPHERAL_LCD) += vout/peripheral_lcd/peripheral_lcd_drv.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_PERIPHERAL_LCD) += vout/peripheral_lcd/peripheral_lcd_debug.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_PERIPHERAL_LCD) += vout/peripheral_lcd/peripheral_lcd_spi.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_PERIPHERAL_LCD) += vout/peripheral_lcd/peripheral_lcd_utils.o

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_PERIPHERAL_LCD) += vout/peripheral_lcd/interface_chip/intel_8080.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_PERIPHERAL_LCD) += vout/peripheral_lcd/interface_chip/spi_st7789.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_PERIPHERAL_LCD) += vout/peripheral_lcd/interface_chip/spi_spd2010.o
