$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_PERIPHERAL_LCD) += vout/peripheral_lcd/peripheral_lcd_drv.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_PERIPHERAL_LCD) += vout/peripheral_lcd/peripheral_lcd_dev.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_PERIPHERAL_LCD) += vout/peripheral_lcd/peripheral_lcd_spi.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_PERIPHERAL_LCD) += vout/peripheral_lcd/interface_spi.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_PERIPHERAL_LCD) += vout/peripheral_lcd/interface_8080.o
