#
# Makefile for the amlogic video device interface device drivers.
#
asflags-y += -mfloat-abi=softfp -mfpu=neon

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_V4L_VIDEO) += video_processor/video_dev/amlvideo.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_V4L_VIDEO2) += video_processor/video_dev/amlvideo2.o
