$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TABLET) += vout/lcd/lcd_tablet/DisplayPort/DP_aux.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TABLET) += vout/lcd/lcd_tablet/DisplayPort/DP_EDID.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TABLET) += vout/lcd/lcd_tablet/DisplayPort/DP_timing.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TABLET) += vout/lcd/lcd_tablet/DisplayPort/DP_training.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TABLET) += vout/lcd/lcd_tablet/DisplayPort/DP_utils.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TABLET) += vout/lcd/lcd_tablet/DisplayPort/DP_debug.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TABLET) += vout/lcd/lcd_tablet/DisplayPort/DP_DACP.o

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TABLET) += vout/lcd/lcd_tablet/DisplayPort/DP_tx.o

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_TABLET) += vout/lcd/lcd_tablet/DisplayPort/lcd_eDP.o
