obj-y += ddr_port_desc.o

obj-$(CONFIG_AMLOGIC_DDR_BANDWIDTH)	+= ddr_bandwidth.o
obj-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_GXL)	+= ddr_band_op_gxl.o
obj-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_GX)	+= ddr_band_op_gx.o
obj-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_G12)	+= ddr_band_op_g12.o
obj-$(CONFIG_AMLOGIC_DDR_BANDWIDTH_A1)	+= ddr_band_op_a1.o

obj-$(CONFIG_AMLOGIC_DMC_MONITOR)	+= dmc_monitor.o
obj-$(CONFIG_AMLOGIC_DMC_MONITOR_G12)	+= dmc_g12.o
obj-$(CONFIG_AMLOGIC_DMC_MONITOR_GX)	+= dmc_gx.o
obj-$(CONFIG_AMLOGIC_DMC_MONITOR_C1)	+= dmc_c1.o
