dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3399-khadas-edge-linux.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3399-khadas-edgev-linux.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3399-khadas-captain-linux.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
