#
# Makefile for the amlogic post process manager drivers.
#

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_POST_PROCESS_MANAGER) += video_processor/ppmgr/ppmgr_drv.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_POST_PROCESS_MANAGER) += video_processor/ppmgr/ppmgr_vpp.o

ccflags-y += -Iinclude/linux/ge2d/
