#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.


obj-$(CONFIG_TOUCHSCREEN_FTS_3427) += focaltech_upgrade_ft3427.o
obj-$(CONFIG_TOUCHSCREEN_FTS_5726) += focaltech_upgrade_ft5726.o
