#
# Makefile for AMLOGIC MTD reserve management for mtd subsystem
#

MODULE_NAME = meson_mtd_reserve
obj-$(CONFIG_MTD_RESV_MESON) = $(MODULE_NAME).o
$(MODULE_NAME)-$(CONFIG_MTD_RESV_MESON) += rsv-manage.o rsv-dev.o rsv-key.o

