#
# (C) COPYRIGHT 2012-2013 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# A copy of the licence is included with the program, and can also be obtained
# from Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA  02110-1301, USA.
#
#
ifeq ($(CONFIG_MALI_MIDGARD),y)
obj-y += platform/devicetree/mali_clock.c
obj-y += platform/devicetree/mpgpu.c
obj-y += platform/devicetree/meson_main2.c
obj-y += platform/devicetree/platform_gx.c
obj-y += platform/devicetree/scaling.c
obj-y += mali_kbase_runtime_pm.c
obj-y += mali_kbase_config_devicetree.c
else ifeq ($(CONFIG_MALI_MIDGARD),m)
SRC += platform/devicetree/mali_clock.c
SRC += platform/devicetree/mpgpu.c
SRC += platform/devicetree/meson_main2.c
SRC += platform/devicetree/platform_gx.c
SRC += platform/devicetree/scaling.c
SRC += platform/devicetree/mali_kbase_runtime_pm.c
SRC += platform/devicetree/mali_kbase_config_devicetree.c
endif
