obj-$(CONFIG_AMLOGIC_CRG)                            += crg/
obj-$(CONFIG_AMLOGIC_CRG)                            += crgdrdphy/
obj-$(CONFIG_AMLOGIC_CRG)                            += crgm31phy/
obj-$(CONFIG_AMLOGIC_USB_DWC_OTG_HCD)	+= dwc_otg/310/
obj-$(CONFIG_AMLOGIC_USB2PHY) 		+= usb2phy/
obj-$(CONFIG_AMLOGIC_USB3PHY) 		+= usb3v2phy/
obj-$(CONFIG_AMLOGIC_USB3PHY) 		+= usb3v3phy/
obj-$(CONFIG_AMLOGIC_USB3PHY) 		+= usbotg/
