obj-$(CONFIG_AML_HDMI_TX_14)		+= hdmitx14.o

hdmitx14-objs := hdmi_tx.o hdmi_tx_video.o hdmi_tx_audio.o hdmi_tx_edid.o hdmi_tx_audio.o hdmi_tx_hdcp.o hdmi_tx_compliance.o hdmi_tx_cec.o hdmi_cec_key.o
obj-$(CONFIG_AML_HDMI_TX_14) += ts/

#EXTRA_CFLAGS += -O2
