$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_EXTERN) += vout/lcd/lcd_extern/lcd_extern.o vout/lcd/lcd_extern/ext_default.o vout/lcd/lcd_extern/mipi_default.o vout/lcd/lcd_extern/ext_i2c_dev.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_EXTERN_I2C_ANX6862_7911) += vout/lcd/lcd_extern/i2c_ANX6862_7911.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_EXTERN_I2C_CS602) += vout/lcd/lcd_extern/i2c_CS602.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_LCD_EXTERN_I2C_OLED) += vout/lcd/lcd_extern/i2c_oled.o
