dtbo-y += uart3.dtbo \
		  pwm_f.dtbo \
		  i2c3.dtbo \
		  spi1.dtbo \
		  onewire.dtbo \
		  disable-ts050.dtbo \
		  m2x-eth.dtbo \
		  otg-device.dtbo \
		  watchdog.dtbo \
		  i2s.dtbo

targets += $(dtbo-y)
always  := $(dtbo-y)
