# Makefile for AMLOGIC PHY drivers

obj-$(CONFIG_AML_ICPLUS)	+= am_icplus.o
obj-$(CONFIG_AML_PHY)		+= am_internal.o
obj-$(CONFIG_AML_MICREL)	+= am_micrel.o
obj-$(CONFIG_AML_SMSC)	+= am_smsc.o
obj-$(CONFIG_AML_REALTEK)	+= am_realtek.o
