$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_VOUT_SERVE) += vout/vout_serve/vout_notify.o vout/vout_serve/vout_serve.o vout/vout_serve/vout_func.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_VOUT2_SERVE) += vout/vout_serve/vout2_notify.o vout/vout_serve/vout2_serve.o

