$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_VOUT_SERVE) += vout/vout_serve/vout_reg.o vout/vout_serve/vout_mux.o vout/vout_serve/vout_sys_serve.o vout/vout_serve/dummy_venc.o vout/vout_serve/vout_notify.o vout/vout_serve/vout_serve.o vout/vout_serve/vout_func.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_VOUT2_SERVE) += vout/vout_serve/vout2_notify.o vout/vout_serve/vout2_serve.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_VOUT3_SERVE) += vout/vout_serve/vout3_notify.o vout/vout_serve/vout3_serve.o

