obj-$(CONFIG_AMLOGIC_SND_SOC_AUGE)	+= clks/
obj-$(CONFIG_AMLOGIC_SND_SOC_AUGE)	+= \
					audio_controller.o \
					audio_io.o \
					card_utils.o \
					tdm.o \
					tdm_hw.o \
					spdif.o \
					spdif_hw.o \
					pdm.o \
					pdm_hw.o \
					iomap.o \
					ddr_mngr.o \
					loopback.o \
					loopback_hw.o \
					audio_utils.o \
					locker.o \
					locker_hw.o \
					resample.o \
					resample_hw.o \
					effects.o \
					effects_hw.o \
					effects_v2.o \
					effects_hw_v2.o \
					sharebuffer.o \
					extn.o \
					frhdmirx_hw.o \
					vad.o \
					vad_hw.o \
					vad_dev.o \
					earc.o \
					earc_hw.o \
					card.o

					#pwrdet.o \
					pwrdet_hw.o \
					#earc.o \
					earc_hw.o \
