#
# Makefile for the DVB driver.
#

obj-$(CONFIG_AM_DVB) += aml.o

aml-objs=aml_dvb.o aml_dmx.o

obj-$(CONFIG_AM_DVB) += aml_fe.o

obj-$(CONFIG_AM_CI) += amlci/

obj-$(CONFIG_AM_DTVDEMOD) += amldemod/

obj-$(CONFIG_AM_ATVDEMOD) += amlatvdemod/

obj-$(CONFIG_AML_SMARTCARD) += smartcard/












































ccflags-y += -I.
