# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_VIDEO_RK_DES_RKX12X)	+= rkdes-rkx12x.o
rkdes-rkx12x-objs	+= \
	hal/cru_core.o \
	hal/cru_rkx120.o \
	hal/cru_rkx121.o \
	hal/pinctrl_rkx120.o \
	rkx12x_remote.o \
	rkx12x_linkrx.o \
	rkx12x_csi2tx.o \
	rkx12x_dvptx.o \
	rkx12x_txphy.o \
	rkx12x_i2c.o \
	rkx12x_v4l2.o \
	rkx12x_dump.o \
	rkx12x_debugfs.o \
	rkx12x_drv.o
