#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_AM_INPUT) += saradc/
obj-$(CONFIG_AM_INPUT) += remote/
obj-$(CONFIG_AM_INPUT) += keyboard/
obj-$(CONFIG_AM_INPUT) += gpio_key/
obj-$(CONFIG_AM_INPUT) += sensor/
obj-$(CONFIG_AM_INPUT) += avin_detect/

