#
# Makefile for the amlogic input  driver.
#

#Each configuration option enables a list of files.

obj-$(CONFIG_AMLOGIC_MESON_IR) += ir/

obj-$(CONFIG_AMLOGIC_INPUT_KEYBOARD) += keyboard/

obj-$(CONFIG_AMLOGIC_INPUT_TOUCHSCREEN) += touchscreen/
