# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_CRYPTO_DEV_ROCKCHIP_CRYPTO) += rkcrypto/
obj-$(CONFIG_CRYPTO_DEV_ROCKCHIP_CE) += rkce/

obj-$(CONFIG_CRYPTO_DEV_ROCKCHIP_DEV) += cryptodev_linux/
