##########################################
########## Amlogic codec memory manager ###############
##########################################

##########################################
## The order of directories matter.
## Do not change.
##########################################


$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_CODEC_MM) += common/codec_mm/configs/configs.o common/codec_mm/configs/configs_module.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_CODEC_MM) += common/codec_mm/configs/configs_test.o


