#
# Makefile for VFM
#

$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_VFM) += common/vfm/vfm.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_VFM) += common/vfm/vframe_provider.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_VFM) += common/vfm/vframe_receiver.o
$(MEDIA_MODULE_NAME)-$(CONFIG_AMLOGIC_MEDIA_VFM) += common/vfm/vftrace.o
