# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_VIDEO_RK_SER_RKX11X)	+= rkser-rkx11x.o
rkser-rkx11x-objs	+= \
	hal/cru_core.o \
	hal/cru_rkx110.o \
	hal/cru_rkx111.o \
	hal/pinctrl_rkx110.o \
	rkx11x_i2c.o \
	rkx11x_rxphy.o \
	rkx11x_csi2host.o \
	rkx11x_vicap.o \
	rkx11x_linktx.o \
	rkx11x_dump.o \
	rkx11x_debugfs.o \
	rkx11x_drv.o
