obj-$(CONFIG_AMLOGIC_GLOBAL_TIMER_CORE) += global_timer_core.o
obj-$(CONFIG_AMLOGIC_GLOBAL_TIMER_ISP) += global_timer_isp.o
obj-$(CONFIG_AMLOGIC_GLOBAL_TIMER_OUTPUT) += global_timer_output.o
obj-$(CONFIG_AMLOGIC_GLOBAL_TIMER_INPUT) += global_timer_input.o
