asflags-y=-mfloat-abi=softfp -mfpu=neon
ccflags-y += -Idrivers/staging/android/

obj-$(CONFIG_AMLOGIC_VIDEO_COMPOSER) += video_composer.o
obj-$(CONFIG_AMLOGIC_VIDEO_COMPOSER) += vframe_ge2d_composer.o